### ISSUE TITLE
Hello ， one question, where need I put the roms in 

### ISSUE THREAD

**Issue by hellangleZ** [diambra/arena#111]
I just put  the rom to "/opt/diambraArena/roms/kof98umh.zip"  but still with this log

My full  path is 

![image](https://github.com/diambra/arena/assets/15274284/542711bd-8fc2-40fe-85cd-0c2d84a2375e)

(0)Environment initialization ...
Error: Cannot open "/opt/diambraArena/roms/kof98umh.zip": No such file or directory.
You need to put the Game rom file in the roms directory.

------------------------------------------------------------------------------------------------------

        Contact support on DIAMBRA Discord Server: https://diambra.ai/discord
                                        AND / OR
 Open a ticket on our GitHub repository issue Tracker: https://github.com/diambra/arena/issues

------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\bozho\AppData\Local\Programs\Python\Python310\lib\site-packages\diambra\arena\engine\interface.py", line 31, in env_init
    response = self.client.EnvInit(env_settings_pb)
  File "C:\Users\bozho\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_channel.py", line 1176, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Users\bozho\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_channel.py", line 1005, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.CANCELLED
        details = "Cannot open "/opt/diambraArena/roms/kof98umh.zip": No such file or directory.
You need to put the Game rom file in the roms directory.
"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-03-31T07:49:50.4674812+00:00", grpc_status:1, grpc_message:"Cannot open \"/opt/diambraArena/roms/kof98umh.zip\": No such file or directory.\nYou need to put the Game rom file in the roms directory.\n"}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bozho\llm-colosseum\98.py", line 34, in <module>
    main()
  File "C:\Users\bozho\llm-colosseum\98.py", line 6, in main
    env = diambra.arena.make("kof98umh", render_mode="human")
  File "C:\Users\bozho\AppData\Local\Programs\Python\Python310\lib\site-packages\diambra\arena\make_env.py", line 43, in make
    env = DiambraGym1P(env_settings)
  File "C:\Users\bozho\AppData\Local\Programs\Python\Python310\lib\site-packages\diambra\arena\arena_gym.py", line 222, in __init__
    super().__init__(env_settings)
  File "C:\Users\bozho\AppData\Local\Programs\Python\Python310\lib\site-packages\diambra\arena\arena_gym.py", line 38, in __init__
    self.env_info = self.arena_engine.env_init(self.env_settings.get_pb_request(init=True))
  File "C:\Users\bozho\AppData\Local\Programs\Python\Python310\lib\site-packages\diambra\arena\engine\interface.py", line 33, in env_init
    raise Exception(CONNECTION_FAILED_ERROR_TEXT)
Exception: DIAMBRA Arena failed to connect to the Engine Server. Are you running it with DIAMBRA CLI: `diambra run python script.py`?

See the docs (https://docs.diambra.ai) for additional details, or join DIAMBRA Discord Server (https://diambra.ai/discord) for support.

**Comment by alexpalms** [comment]
@hellangleZ thanks for reaching out. 
Two main points:
1) You can use the CLI to check the roms you have in your local folder: 
`diambra arena check-roms /absolute/path/to/roms/folder/romFileName.zip` (docs reference here: https://docs.diambra.ai/#download-game-roms-and-check-validity)
2)  In the same section, there is the base command to run a script:
`diambra run -r /absolute/path/to/roms/folder/ python script.py` have you made sure to use the `-r` to pass the absolute path of the local folder where you put you r roms?

That should solve your issue
